# Generated by Django 5.2.7 on 2025-10-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_4',
            field=models.URLField(blank=True, verbose_name='Image 4'),
        ),
    ]
