# Generated by Django 5.2.7 on 2025-10-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url_2_product_image_url_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_5',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_6',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
